# Generated by Django 5.2.1 on 2025-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0002_pet_picture_alter_vaccinationcard_rabies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationcard',
            name='rabies',
            field=models.DateField(default='2025-05-20'),
        ),
        migrations.AlterField(
            model_name='vetvisit',
            name='date',
            field=models.DateField(default='2025-05-20'),
        ),
    ]
