# Generated by Django 5.2.4 on 2025-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets_app", "0003_alter_vaccinationcard_rabies_alter_vetvisit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinationcard",
            name="rabies",
            field=models.DateField(default="2025-07-21"),
        ),
        migrations.AlterField(
            model_name="vetvisit",
            name="date",
            field=models.DateField(default="2025-07-21"),
        ),
    ]
