# Generated by Django 5.2.1 on 2025-07-22 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets_app", "0004_alter_vaccinationcard_rabies_alter_vetvisit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="card",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pets_app.vaccinationcard",
            ),
        ),
    ]
