# Generated by Django 5.2.1 on 2025-07-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets_app", "0005_alter_pet_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccinationcard",
            name="rabies",
            field=models.DateField(default="2025-07-22"),
        ),
        migrations.AlterField(
            model_name="vetvisit",
            name="date",
            field=models.DateField(default="2025-07-22"),
        ),
    ]
